# Generated by Django 5.1.2 on 2024-11-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_education_human_professionalexperience_sumary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='servise_image/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
